name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: "8.0.x"
        - run: dir
        - run: dotnet build NahidaImpact.sln
        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: D:\a\turbo-computing-machine\turbo-computing-machine\
        #- name: Download all workflow run artifacts
        #  uses: actions/download-artifact@v3
    
