name: Context testing
on: 
    workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

      steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - run: dir
        - name: build
          run: dotnet build NahidaImpact.sln
        - run: dir
