name: Context testing
on: 
    workflow_dispatch:

steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - run: dir
    - name: Build
      run: dotnet build NahidaImpact.sln
    - run: dir
